services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydb"
      PORT: "3000"
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:3000"
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  db_data:

networks:
  default:
    name: local-network
    external: true

# networks:
#   app-network:
#     driver: bridge
